# Generated by Django 4.2.2 on 2023-06-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='section_photos/')),
                ('photo_material', models.ImageField(blank=True, null=True, upload_to='photo_material_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='section_videos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='section_documents/')),
                ('material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_question', models.IntegerField(default=0)),
                ('total_correct_answer', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='statistic',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='section_photos/')),
                ('status', models.BooleanField(default=False)),
                ('material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.lesson')),
                ('test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.testing')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('choice1', models.CharField(default='вариант', max_length=200)),
                ('choice2', models.CharField(default='вариант', max_length=200)),
                ('choice3', models.CharField(default='вариант', max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('user_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.testing')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.testing'),
        ),
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='users', to='Quiz.section'),
        ),
    ]
