# Generated by Django 4.2.2 on 2023-06-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_alter_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='material',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='test',
        ),
    ]
